// This file was generated by the ExaHyPE toolkit.
// It will not be overwritten.
//
//
// ========================
//   www.exahype.eu
// ========================
#include "IntegralsWriter.h"


Euler::IntegralsWriter::IntegralsWriter(MyEulerSolver&  solver) {
  // @TODO Please insert your code here.
}

Euler::IntegralsWriter::~IntegralsWriter() {
}

void Euler::IntegralsWriter::startPlotting( double time) {
  // @TODO Please insert your code here.
}


void Euler::IntegralsWriter::finishPlotting() {
  // @TODO Please insert your code here.
}

void Euler::IntegralsWriter::mapQuantities(
    const tarch::la::Vector<DIMENSIONS, double>& offsetOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& sizeOfPatch,
    const tarch::la::Vector<DIMENSIONS, double>& x,
    const tarch::la::Vector<DIMENSIONS, int>&    pos,
    double* Q,
    double* outputQuantities,
    double timeStamp
) {
  const int writtenUnknowns = 0;
  for (int i=0; i<writtenUnknowns; i++){ 
    outputQuantities[i] = Q[i];
  }
}