#!/bin/bash
#
# This is a standalone bash script to determine the Java Development Toolkit
# (Java compiler) version. While the runtime version is typically easy to get,
# i.e. "java -version", there is no consistent way of getting the JDK version
# without compiling a java file and inspecting its code. This is exactly what
# this script is doing.
#
# Written by SvenK at 2017-10-10, Public Domain for ExaHyPE.
#

workdir=$(mktemp -d)
cd $workdir

TestClass="TestClass"

cat > ${TestClass}.java <<JAVACODE
/* This code was generated by $0 for a standalone javac version check */
public class $TestClass {
	public static void main(String[] args) {
		System.out.println(System.getProperty("java.version"));
	}
}
JAVACODE

javac ${TestClass}.java

JRE_VERSION=$(java $TestClass)
JDK_MAJOR_VERSION=$(javap -verbose $TestClass | awk '/major/{print $3;}')

# a way to map JDK major versions to the usual version names.
# Source for instance: https://stackoverflow.com/q/9170832
JDK_VERSION=$(( JDK_MAJOR_VERSION - 44))

# a verbose text for ExaHyPE. Replace as you like.
echo "On your machine, JRE java version $JRE_VERSION and JDK javac compiler version $JDK_VERSION was detected."

rm -rf $workdir