#!/bin/bash
#
# Generate the combinations from the GRMHD_cpp_Shocktubes.mexa file.

MEXA="exa gmexa"
infile="GRMHD_cpp_Shocktubes.mexa"

mkdir -p Specfiles

# todo: Obtain the combinations from the mexa file itself
#       and just iterate instead of doing this here.

for solver in DG FV Limiting; do
	solverkey="${solver}Solver"
	for simulation in RP1; do
		simulationkey="Shocktubes/${simulation}"
		dim=2
		
		outfile="Specfiles/${infile/.*}-${simulation}-${solver}-${dim}D.exahype"
		tmpfile=$(mktemp)
		
		echo "Making $outfile ..."
  
		$MEXA specfile  --parameter-style=adapted \
		  --infile $infile --outfile $tmpfile \
		  --add Simulation=$simulationkey \
		  --add Solver=$solverkey
		  
		if [ -e $outfile ] && ! diff $outfile $tmpfile; then
			echo "$outfile has local changes, is not overwritten. Delete to recreate."
		else
			mv $tmpfile $outfile
			#cat <(echo "/* Generated by $0 from $infile at $(date) */") $tmpfile > $outfile
		fi
done
done
